import "@/styles/globals.css";
import Head from "next/head";
import Nav from "@/component/Nav";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Toy Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/half-moon.png" />
      </Head>
      <Nav />
      <Component {...pageProps} />
    </>
  );
}
