/* eslint-disable @next/next/no-sync-scripts */
import "@/styles/globals.css";
import Head from "next/head";
import Nav from "@/component/Nav";
import { RecoilRoot } from "recoil";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>SoyesKids AI Avatar Platform</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/half-moon.png" />
      </Head>
      <RecoilRoot>
        <Nav />
        <Component {...pageProps} />
      </RecoilRoot>
      <script src="https://cubism.live2d.com/sdk-web/cubismcore/live2dcubismcore.min.js"></script>
      <script src="https://cdn.jsdelivr.net/gh/dylanNew/live2d/webgl/Live2D/lib/live2d.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/pixi.js@6.5.2/dist/browser/pixi.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/pixi-live2d-display/dist/index.min.js"></script>
      {/* <script src="https://cdn.jsdelivr.net/npm/request/index.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/request/request.js"></script> */}
    </>
  );
}
