import Head from "next/head";
import styled from "styled-components";
import { FlexContainer, StyledButton } from "../styled-component/common";

export default function Home() {
  return (
    <>
      <Head>
        <title>Toy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <FlexContainer justify="center" align="center" dir="col" height="100vh">
          <HomeSpan>Welcome My Toy Project</HomeSpan>
          <StyledButton>Button</StyledButton>
        </FlexContainer>
      </main>
    </>
  );
}

const HomeSpan = styled.span`
  font-size: 3rem;
  font-weight: bold;
`;
